# Generated by Gemini

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0002_alter_mantenimiento_estado_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='evidencia',
            field=models.FileField(blank=True, default='', upload_to='evidencias_mantenimiento/'),
        ),
    ]
