# Generated by Gemini

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0003_add_evidencia_finalizacion_and_alter_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='evidencia',
            field=models.FileField(default='', upload_to='evidencias_mantenimiento/'),
        ),
    ]
