# Generated by Django 5.2.8 on 2025-12-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AddField(
            model_name='sede',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='pais',
            field=models.CharField(default='Colombia', max_length=100),
        ),
    ]
