# Generated by Django 5.2.8 on 2025-11-26 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipo_mantenimiento_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre o descripción del periférico, ej: Mouse Logitech G203', max_length=100)),
                ('tipo', models.CharField(choices=[('Mouse', 'Mouse'), ('Teclado', 'Teclado'), ('Base', 'Base'), ('Cargador', 'Cargador'), ('Monitor', 'Monitor'), ('Otro', 'Otro')], max_length=50)),
                ('estado_tecnico', models.CharField(choices=[('Funcional', 'Funcional'), ('Con fallas', 'Con fallas'), ('Dañado', 'Dañado')], default='Funcional', max_length=50)),
                ('estado_disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Devuelto', 'Devuelto')], default='Disponible', max_length=50)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('equipo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos', to='inventory.equipo')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
