# Generated by Django 5.2.8 on 2025-11-26 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_periferico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_licencia', models.CharField(choices=[('Sistema Operativo', 'Sistema Operativo'), ('Office', 'Office'), ('Otro', 'Otro')], max_length=50)),
                ('tipo_activacion', models.CharField(choices=[('Original', 'Original'), ('Pirateada', 'Pirateada'), ('OEM', 'OEM'), ('Volumen', 'Volumen')], max_length=50)),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_instalacion', models.DateField()),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Vencida', 'Vencida')], default='Activa', max_length=50)),
                ('notas', models.TextField(blank=True, null=True)),
                ('equipo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='inventory.equipo')),
            ],
        ),
    ]
