# Generated by Django 5.2.8 on 2025-11-26 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_licencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasisalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Con Pendientes', 'Con Pendientes'), ('Rechazado', 'Rechazado')], max_length=50)),
                ('detalles_pendientes', models.TextField(blank=True, help_text='Detalles de equipos, periféricos o mantenimientos pendientes.', null=True)),
                ('pdf_url', models.URLField(blank=True, help_text='URL del PDF del pasisalvo generado.', max_length=500, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasisalvos_generados', to=settings.AUTH_USER_MODEL)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasisalvos_creados_por_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paz y Salvo',
                'verbose_name_plural': 'Paz y Salvos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
