# Generated by Django 5.2.8 on 2025-11-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_pasisalvo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observacion_devolucion', models.TextField(blank=True, null=True, verbose_name='Observación de Devolución')),
                ('equipo_asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipo', verbose_name='Equipo Asociado en la Entrega')),
                ('periferico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='inventory.periferico')),
                ('usuario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.usuario', verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Historial de Periférico',
                'verbose_name_plural': 'Historial de Periféricos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
    ]
