# Generated by Django 5.2.8 on 2025-11-28 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_historialperiferico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='equipo',
            name='area_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área del Usuario'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cargo_jefe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Jefe Inmediato'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='cargo_usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Usuario'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_entrega_a_colaborador',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega a Colaborador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_recibido_satisfaccion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Recibo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='firma_compromiso',
            field=models.TextField(blank=True, null=True, verbose_name='Firma de Compromiso'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='firma_recibido_jefe',
            field=models.TextField(blank=True, null=True, verbose_name='Firma de Recibido del Jefe'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='firma_recibido_usuario',
            field=models.TextField(blank=True, null=True, verbose_name='Firma de Recibido del Usuario'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='nombre_jefe',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Jefe Inmediato'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='observaciones_usuario',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del Usuario al Recibir'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ram',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Memoria RAM'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='responsable_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_entregados', to='inventory.usuario', verbose_name='Responsable de la Entrega (TI)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='rom',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Almacenamiento (ROM)'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación Física'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado_disponibilidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('Reservado', 'Reservado'), ('No disponible por daño', 'No disponible por mantenimiento')], default='Disponible', max_length=50, verbose_name='Estado de Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado_tecnico',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Funcional', 'Funcional'), ('Con fallas', 'Con fallas'), ('Dañado', 'Dañado'), ('Desguazado', 'Desguazado'), ('En reparación', 'En reparación')], default='Funcional', max_length=50, verbose_name='Estado Técnico'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas (TI)'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.sede', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='serial',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='inventory.usuario', verbose_name='Usuario Asignado'),
        ),
    ]
