# Generated by Django 5.2.8 on 2025-12-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_equipo_options_remove_equipo_fecha_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='responsable_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_entregados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la Entrega (TI)'),
        ),
        migrations.AlterField(
            model_name='historialperiferico',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='area_usuario',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='cargo_usuario',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_entrega_a_colaborador',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='firma_recibido_usuario',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='observaciones_usuario',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ubicacion_fisica',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_mantenimiento/'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
