# Generated by Django 5.2.8 on 2025-12-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_equipo_responsable_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_proximo_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Próximo Mantenimiento'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Último Mantenimiento'),
        ),
    ]
