# Generated by Django 5.2.8 on 2025-12-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_equipo_fecha_proximo_mantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha_entrega_a_colaborador',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega a Colaborador'),
        ),
    ]
