# Generated by Django 5.2.8 on 2025-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_equipo_fecha_entrega_a_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='firma_recibido_usuario',
            field=models.TextField(blank=True, null=True, verbose_name='Firma de Recibido del Colaborador'),
        ),
    ]
