# Generated by Django 5.2.8 on 2025-12-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('inventory', '0011_equipo_firma_recibido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='usuario_asignado',
        ),
        migrations.RemoveField(
            model_name='historialperiferico',
            name='usuario_asignado',
        ),
        migrations.RemoveField(
            model_name='periferico',
            name='usuario_asignado',
        ),
        migrations.AddField(
            model_name='equipo',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_asignados', to='empleados.empleado', verbose_name='Empleado Asignado'),
        ),
        migrations.AddField(
            model_name='historialperiferico',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado', verbose_name='Empleado Asignado'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos_asignados', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='pasisalvo',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasisalvos_generados', to='empleados.empleado'),
        ),
    ]
