# Generated by Django 5.2.8 on 2025-12-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_equipo_usuario_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='antivirus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antivirus Instalado'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='procesador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='redes_conectadas',
            field=models.TextField(blank=True, null=True, verbose_name='Redes Conectadas'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='sistema_operativo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Servidor', 'Servidor'), ('Tablet', 'Tablet'), ('Movil', 'Movil'), ('Otro', 'Otro')], default='Desktop', max_length=50, verbose_name='Tipo de Equipo'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='usuarios_sistema',
            field=models.TextField(blank=True, null=True, verbose_name='Usuarios del Sistema Operativo'),
        ),
    ]
