# Generated by Django 5.2.8 on 2025-12-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_equipo_antivirus_equipo_procesador_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
