# Generated by Django 5.0.4 on 2024-05-18 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_delete_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('tipo_accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado')], max_length=20, verbose_name='Tipo de Acción')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='inventory.equipo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Historial de Equipo',
                'verbose_name_plural': 'Historial de Equipos',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
