# Generated by Django 5.2.8 on 2025-12-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_historialequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
