# Generated by Django 5.2.8 on 2026-01-06 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_equipo_activo'),
        ('sede', '0002_alter_sede_options_sede_ciudad_sede_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sede.sede', verbose_name='Sede'),
        ),
    ]
