# Generated by Django 5.2.8 on 2026-01-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_equipo_sede'),
        ('usuarios', '0004_alter_userprofile_sede'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
