# Generated by Django 5.2.8 on 2026-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_userprofile_area_userprofile_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USUARIO', 'Usuario')], default='USUARIO', max_length=20),
        ),
    ]
